server:
  port: 8090

spring:
  application:
    name: test-quartz-demo
  datasource:
    name: ds0
    url: jdbc:mysql://localhost:3306/quartz?useSSL=false&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      pool-name: test/ds0
      connection-timeout: 45000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 5
      minimum-idle: 0
      connection-test-query: "select 1"
      validation-timeout: 1000
      isolate-internal-queries: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            dataSource: ds0
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

mybatis:
  type-aliases-package: com.myself.quartz.test
  mapper-locations: classpath*:/mapper/**/*.xml